window.CONFIG = {
  appName: '观鸟路线记录',
  locationSource: 'gps',
  defaultCenter: {
    lat: 31.2304,
    lng: 121.4737,
    label: '默认起点',
  },
  defaultZoom: 16,
  activeProvider: 'tianditu',
  providers: {
    tianditu: {
      name: '天地图',
      token: 'b426c98dce2a97cf4419eb8fc81c249b',
      attribution: '&copy; 天地图',
      errorHint: '地图瓦片加载失败，请检查网络、服务 Key 或切换公共地图源。',
      layers: [
        {
          key: 'tianditu-vector',
          url: 'https://t{s}.tianditu.gov.cn/vec_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=vec&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk={token}',
          subdomains: '01234567',
          maxZoom: 18,
        },
        {
          key: 'tianditu-label',
          url: 'https://t{s}.tianditu.gov.cn/cva_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=cva&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk={token}',
          subdomains: '01234567',
          maxZoom: 18,
        },
      ],
    },
    osm: {
      name: 'OpenStreetMap',
      attribution: '&copy; OpenStreetMap contributors',
      errorHint: '地图瓦片加载较慢或失败，可在配置中切换瓦片源。',
      layers: [
        {
          key: 'osm-standard',
          url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
          maxZoom: 19,
        },
      ],
    },
  },
  storageKey: 'bird-route-current-session',
  historyStorageKey: 'bird-route-history',
  shareImport: {
    serviceEnabled: false,
    duplicateStrategy: 'openExisting',
    sharedLocationScope: 'fullRoute',
    pendingServiceLabel: '服务器链接服务待接入',
  },
  fuzzyMatch: {
    uncertainSpeciesName: '未确定鸟种',
    featureGroups: [
      {
        key: 'size',
        label: '体型',
        multiple: false,
        options: [
          { value: 'tiny', label: '很小' },
          { value: 'small', label: '小型' },
          { value: 'medium', label: '中型' },
          { value: 'large', label: '大型' },
          { value: 'veryLarge', label: '很大' },
        ],
      },
      {
        key: 'colors',
        label: '主色',
        multiple: true,
        options: [
          { value: 'white', label: '白' },
          { value: 'black', label: '黑' },
          { value: 'gray', label: '灰' },
          { value: 'brown', label: '褐' },
          { value: 'yellow', label: '黄' },
          { value: 'green', label: '绿' },
          { value: 'blue', label: '蓝' },
          { value: 'red', label: '红' },
        ],
      },
      {
        key: 'behaviors',
        label: '行为',
        multiple: true,
        options: [
          { value: 'swimming', label: '游水' },
          { value: 'wading', label: '涉水' },
          { value: 'flying', label: '飞行' },
          { value: 'soaring', label: '盘旋' },
          { value: 'perching', label: '停栖' },
          { value: 'foragingGround', label: '地面觅食' },
          { value: 'diving', label: '潜水' },
          { value: 'calling', label: '鸣叫' },
        ],
      },
      {
        key: 'habitats',
        label: '栖息地',
        multiple: true,
        options: [
          { value: 'wetland', label: '湿地/湖泊' },
          { value: 'river', label: '河流' },
          { value: 'forest', label: '林地' },
          { value: 'shrub', label: '灌丛' },
          { value: 'grassland', label: '草地' },
          { value: 'farmland', label: '农田' },
          { value: 'urban', label: '城市' },
          { value: 'coast', label: '海岸' },
        ],
      },
      {
        key: 'postures',
        label: '姿态',
        multiple: true,
        options: [
          { value: 'floating', label: '浮在水面' },
          { value: 'longLegs', label: '长腿站立' },
          { value: 'upright', label: '直立' },
          { value: 'tailUp', label: '尾上翘' },
          { value: 'climbing', label: '攀爬树干' },
          { value: 'hovering', label: '悬停' },
          { value: 'soaring', label: '展翅滑翔' },
        ],
      },
    ],
    candidateRules: [
      {
        name: '大天鹅',
        scientificName: 'Cygnus cygnus',
        traits: {
          size: ['large', 'veryLarge'],
          colors: ['white'],
          behaviors: ['swimming'],
          habitats: ['wetland', 'river'],
          postures: ['floating'],
        },
      },
      {
        name: '绿头鸭',
        scientificName: 'Anas platyrhynchos',
        traits: {
          size: ['medium'],
          colors: ['green', 'brown', 'gray'],
          behaviors: ['swimming'],
          habitats: ['wetland', 'river', 'urban'],
          postures: ['floating'],
        },
      },
      {
        name: '苍鹭',
        scientificName: 'Ardea cinerea',
        traits: {
          size: ['large'],
          colors: ['gray', 'white', 'black'],
          behaviors: ['wading', 'flying'],
          habitats: ['wetland', 'river', 'farmland'],
          postures: ['longLegs', 'upright'],
        },
      },
      {
        name: '白鹭',
        scientificName: 'Egretta garzetta',
        traits: {
          size: ['medium'],
          colors: ['white'],
          behaviors: ['wading', 'flying'],
          habitats: ['wetland', 'river', 'farmland', 'coast'],
          postures: ['longLegs'],
        },
      },
      {
        name: '黑水鸡',
        scientificName: 'Gallinula chloropus',
        traits: {
          size: ['medium'],
          colors: ['black', 'gray', 'red'],
          behaviors: ['swimming', 'wading'],
          habitats: ['wetland', 'river'],
          postures: ['tailUp', 'floating'],
        },
      },
      {
        name: '麻雀',
        scientificName: 'Passer montanus',
        traits: {
          size: ['small'],
          colors: ['brown', 'gray'],
          behaviors: ['perching', 'foragingGround'],
          habitats: ['urban', 'farmland', 'shrub'],
          postures: ['upright'],
        },
      },
      {
        name: '白头鹎',
        scientificName: 'Pycnonotus sinensis',
        traits: {
          size: ['small', 'medium'],
          colors: ['gray', 'white', 'brown'],
          behaviors: ['perching', 'calling'],
          habitats: ['urban', 'forest', 'shrub'],
          postures: ['upright'],
        },
      },
      {
        name: '红隼',
        scientificName: 'Falco tinnunculus',
        traits: {
          size: ['medium'],
          colors: ['brown', 'gray'],
          behaviors: ['hovering', 'soaring', 'flying'],
          habitats: ['grassland', 'farmland', 'urban'],
          postures: ['hovering', 'soaring'],
        },
      },
    ],
  },
  mapInteraction: {
    pickingHint: '点击地图确认起点',
    recordingHint: '开发模式：点击地图模拟行走轨迹',
    gpsPendingHint: '正在获取当前位置，请允许浏览器定位权限。',
  },
  gps: {
    enableHighAccuracy: true,
    maximumAgeMs: 0,
    timeoutMs: 10000,
  },
  birdPoint: {
    clusterDistancePx: 36,
  },
};
